Compiling model...
'compile' took 0.000871 s
Training model...
Traceback (most recent call last):
  File "c:\Users\86189\ScaML-Experiment\results\Explicit_Solution_Example\experiment_run.py", line 56, in <module>
    trained_net=optimizer.train("results/Explicit_Solution_Example/model.pth",cycle=40,adam_every=500,lbfgs_every=10,metrics=["l2 relative error","mse"]).net
  File "c:\Users\86189\ScaML-Experiment\results\Explicit_Solution_Example\..\..\optimizers\Adam_LBFGS.py", line 37, in train
    self.model.train(iterations=adam_every, display_every=10)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\model.py", line 636, in train
    self._test()
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\model.py", line 825, in _test
    ) = self._outputs_losses(
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\model.py", line 546, in _outputs_losses
    outs = outputs_losses(inputs, targets, auxiliary_vars)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\model.py", line 320, in outputs_losses_train
    return outputs_losses(
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\model.py", line 308, in outputs_losses
    losses = losses_fn(targets, outputs_, loss_fn, inputs, self, aux=aux)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\data\data.py", line 13, in losses_train
    return self.losses(targets, outputs, loss_fn, inputs, model, aux=aux)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\data\pde.py", line 175, in losses
    error = bc.error(self.train_x, inputs, outputs, beg, end)
  File "C:\Users\86189\Anaconda3\lib\site-packages\deepxde\icbc\boundary_conditions.py", line 162, in error
    return self.func(inputs, outputs, X)[beg:end]
TypeError: Explict_Solution_Example.terminal_constraint() takes 2 positional arguments but 4 were given